### ISSUE TITLE
What is the open source license of the MateDealer project?

### ISSUE THREAD

**Issue by yvandb** [Bouni/MateDealer#3]
The license file describes an MIT-like license but most .h/.c files refer to GPL.
(Last commit removes some other GPL declarations)
Thank you!

**Comment by Bouni** [comment]
Actually, I never really thought what licence may be the best for this project.
Ithink I'll updated all the files to be MIT licenced as of now.

**Comment by yvandb** [comment]
My favorite answer. Thank you.
